title: "Portfólio de Lúcio Benfica"
description: "Análise de Dados, Modelagem Computacional e Inteligência Artificial aplicadas a problemas reais"
theme: just-the-docs

# Links de contato/redes
social_links:
  github: https://github.com/benfluc
  linkedin: https://www.linkedin.com/in/lúcio-j-benfica-6903a3103/
  medium: https://medium.com/@luciojuniobenfica2
