# Site settings
title: Lúcio Benfica Portfólio
description: Projetos e textos sobre Inteligência Artificial e Ciência de Dados
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lúcio Benfica
user_description:
  I am a Data Analyst and Master's student in Computational Modeling,
  with postgraduate degrees in Data Science and Production Engineering.
  This portfolio showcases my projects, articles, and work in data analysis,
  predictive modeling, and data visualization.
user_title: Data Analyst
email: luciojuniobenfica2@gmail.com
linkedin_username: lúcio-j-benfica-6903a3103
github_username:  Benfluc
medium_username::  luciojuniobenfica2

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
